name: Build development image

on:
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the image id
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_ENV"

      - name: Extract branch name
        shell: bash
        run: echo "IMAGE_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.development
          push: true
          tags: ${{ env.IMAGE_ID}}:${{ env.IMAGE_BRANCH }}_development
          platforms: linux/amd64,linux/arm64
