name: Create requirements.txt for dependabot

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  group: requirements-${{ github.head_ref }}
  cancel-in-progress: false
  
jobs:
  build:
    name: requirements.txt
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build requirements.txt
        run: |
          for l in 60 61 62; do
            mkdir -p dependabot/plone$l
            python docker/create-constraints.py \
                   docker/constraints$l.cfg dependabot/plone$l/requirements.txt
          done
      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain dependabot)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Build SBOM
        if: steps.git-check.outputs.changed == 'true'
        run: |
          pip install sbom4python==0.12.5
          mkdir -p sbom
          for l in 60 61 62; do
            sbom4python --requirement dependabot/plone$l/requirements.txt \
                        --sbom spdx --format json --output sbom/plone$l.spdx.json
          done
      - name: Commit and push changes
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config --global user.email "info@redturtle.it"
          git config --global user.name "RedTurtle CI BOT"
          git add dependabot sbom
          git commit -m "Auto-generate file at $(date)" || exit 0
          git pull --rebase "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "${HEAD_REF}"
          git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "HEAD:refs/heads/${HEAD_REF}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
